server:
  port: 8080

server:
  port: 8088

spring:
  ## Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9093
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: localConsumer, remoteConsumer
      key-deserializer: com.stas.learning.messaging.kafka.serializers.DataKeyDeserializer
      value-deserializer: com.stas.learning.messaging.kafka.serializers.DataJsonDeserializer
      #properties.spring.json.key.default.type: java.lang.String
      #properties.spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      #properties.spring.deserializer.value.delegate.class: com.epam.edp.insurance.contract.impl.kafka.JacksonZoneDateTimeDeserializer
      properties.spring.json.trusted.packages: '*'
    producer:
      key-serializer: com.stas.learning.messaging.kafka.serializers.DataKeySerializer
      value-serializer: com.stas.learning.messaging.kafka.serializers.DataJsonSerializer
      properties.spring.json.trusted.packages: '*'
app:
  kafka:
    input:
      topic: input.topic.1
    output:
      topic: output.topic.1
    data:
      topic: transport.topic
    onereq:
      topic: topic.1.req
    oneres:
      topic: topic.1.res
    data:
      topic: transport.topic
    onereq:
      topic: topic.1.req
    oneres:
      topic: topic.1.res
