server:
  port: 8080

spring:
  application.name: ms-kafka-service
  ## Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9093
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
      group-id: localConsumer, remoteConsumer
      key-deserializer: com.stas.learning.messaging.kafka.serializers.DataKeyDeserializer
      value-deserializer: com.stas.learning.messaging.kafka.serializers.DataJsonDeserializer
      #properties.spring.json.key.default.type: java.lang.String
      #properties.spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      #properties.spring.deserializer.value.delegate.class: com.epam.edp.insurance.contract.impl.kafka.JacksonZoneDateTimeDeserializer
      properties.spring.json.trusted.packages: '*'
    producer:
      key-serializer: com.stas.learning.messaging.kafka.serializers.DataKeySerializer
      value-serializer: com.stas.learning.messaging.kafka.serializers.DataJsonSerializer
      properties.spring.json.trusted.packages: '*'
app:
  kafka:
    input:
      topic: input.topic.1
    output:
      topic: output.topic.1
    data:
      topic: transport.topic
    onereq:
      topic: topic.1.req
    oneres:
      topic: topic.1.res
    tx.data.topic: data.tx.topic
  file:
    storage:
      endpoint: test.hcp-demo.hcpdemo.com
      namespace: hitachi-emulator
      secretKey: b144ef4a51d09eb8878c77bdc4ee8e6e
      accessKey: dGVuYW50LXRlc3Q=

logging.level:
  ROOT: INFO
  com.stas: DEBUG