server:
  port: 8082

spring:
  application.name: kafka-transactions
  ## Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  ## Kafka
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
      group-id: some-consumer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          json:
            key.default.type: java.lang.String
            trusted.packages: '*'
        isolation.level: read_committed
    producer:
      transaction-id-prefix: tx-test-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties.spring.json.trusted.packages: '*'

app:
  kafka:
    topic: some.topic.1
    send.to.topic: some.topic.2
    end.topic: end.topic
    tx:
      data:
        topic: data.tx.topic

logging:
  level:
    ROOT: INFO
    org.springframework.kafka: DEBUG