version: '3'
networks:
  default:
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9093:9093"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,DEV://:9093
      #creating listeners for internal access from docker and for development on localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,DEV://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DEV:PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/docker/kafka/logs:/logs
      - /tmp/docker/kafka/data:/data
      - /tmp/docker/kafka/kafka-logs:/kafka
